
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 28 12:51:29 EST 2011
//----------------------------------------------------

package cs665;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FLOATNUMBER = 26;
  public static final int TIMES = 5;
  public static final int IDENT = 27;
  public static final int PLUS = 3;
  public static final int RPAREN = 8;
  public static final int INT = 13;
  public static final int EQUAL = 20;
  public static final int WHILE = 24;
  public static final int SEMI = 2;
  public static final int RCURLY = 10;
  public static final int RETURN = 19;
  public static final int GREATER = 22;
  public static final int TRUE = 17;
  public static final int IF = 23;
  public static final int LPAREN = 7;
  public static final int LCURLY = 9;
  public static final int BOOLEAN = 16;
  public static final int FLOAT = 12;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int FALSE = 18;
  public static final int MINUS = 4;
  public static final int FINAL = 15;
  public static final int PRINT = 11;
  public static final int error = 1;
  public static final int ASSIGN = 14;
  public static final int LESS = 21;
}

